### ISSUE TITLE
빌드 후 실행 시 포톤 연결이 되지 않음

### ISSUE THREAD

**Issue by pid011** [TIMILUM/Esper-Fighters-Cup#21]
에디터에서 실행 시에는 연결이 잘 되나 빌드 후 서버 연결을 시도하면 응답이 오지 않습니다.

이전에 추가한 AppId 로드 관련 문제인 줄 알았는데 로드 관련 코드를 주석처리하고 설정파일에 AppId를 추가 후 테스트 해봤는데 증상은 동일합니다.

@ounols @chlgdutjn7 다른 분들은 빌드파일로 연결 잘 되시나요?

**Comment by ounols** [comment]
띠용.. 빌드는 안해봐서 전혀 몰랐네요... 한번 확인해보겠습니다.

**Comment by pid011** [comment]
Fixed #22
