### ISSUE TITLE
ObjectBase를 상속하는 모든 컴포넌트의 유니티 이벤트 메소드 virtual로 변경

### ISSUE THREAD

**Issue by pid011** [TIMILUM/Esper-Fighters-Cup#28]
현재 유니티 이벤트 메소드를 상속하는 방법들이 중구난방하게 되어 있습니다.
어떤 곳은 virtual을 사용하고 어떤 곳은 new 키워드를 사용해서 덮어쓰는 곳도 있는데 통일이 필요해 보입니다.

또는 베이스 오브젝트에서 private로 구현했다가 상속된 클래스에서 구현된 내용을 모르고 private로 또 구현해서 부모클래스의 이벤트 메소드가 덮어씌워지는 경우도 있을 것 같습니다.

그래서 차라리 자주쓰는 이벤트 메소드들에 한해서 ObjectBase에 virtual로 구현한 다음 이벤트 메소드 구현할 때 마다 override로 구현하고 `base.Update()` 처럼 부모 이벤트 메소드 호출하도록 하는 것이 좋을 것 같은데 다른 분들 의견은 어떠신가요

**Comment by ounols** [comment]
저도 이거에 대해 고민이 많았는데 아직까지 이걸 판단할 수 있는 방식이 직접 상속된 클래스에 들어가는 것 밖에 없더군요....
관련해서 작성해주신 대안처럼 적용하는 것도 좋다고 생각합니다.

이번주차에 서로 작업물 머지하면 제가 수정하도록 할까요?
