### ISSUE TITLE
가끔씩 마우스를 통한 조작이 먹통이 되는 현상

### ISSUE THREAD

**Issue by pid011** [TIMILUM/Esper-Fighters-Cup#37]
![Honeycam 2021-10-21 07-30-56](https://user-images.githubusercontent.com/11596519/138181589-ff32cb43-ad43-471a-b110-a66f5ec1a35a.gif)

플레이어가 마우스를 따라 돌아보지 않고 마우스 방향으로 스킬을 사용하지도 못하는 현상

**Comment by chlgdutjn7** [comment]
이거 아마 제가 들어올리기 스킬을 쓸때 애니메이션 확인 하려고 막아놨던거 때문에 안되는거 같습니다.
수정해서 올리겠습니다.
